Controllers/ArtController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Helpers;
using Models;

namespace ArtManager.Controllers
{
    public class ArtController : Controller
    {
        private readonly ArtContext _context;
        private IHostingEnvironment _env; //håller reda på sökvägar
        private readonly IDeleteArtImages _deleteArtImages;

        public ArtController(ArtContext context, IHostingEnvironment env, IDeleteArtImages deleteArtImages)
        {
            _context = context;
            _env = env;
            _deleteArtImages = deleteArtImages;
        }

        // GET: Art
        public async Task<IActionResult> Index()
        {
            return View(await _context.Arts.ToListAsync());
        }

        // GET: Art/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var art = await _context.Arts
                .FirstOrDefaultAsync(m => m.ArtId == id);
            if (art == null)
            {
                return NotFound();
            }


            //Loading/show current picture
            string imagePathAndName = art.ImagePath;
            imagePathAndName += "/" + art.ImageName;
            ViewBag.imagePathAndName = imagePathAndName;


            return View(art);
        }

        // GET: Art/Create
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ArtId,Name,Artist,Description,Price,PriceText,ImageName,ImagePath,ImageWidths,ImageOriginal,Hidden")] Art art, IFormFile ImgFile)
        {

            if (ImgFile == null && ImgFile.Length > 0)
            {
                //throw new ServiceException(ServiceErrorCodes.InvalidPhoto, "There is no photo.");
                return Content("File not found");
            }
            //Get application directory
            string webRoot = _env.WebRootPath;

            if (ModelState.IsValid)
            {
                var loadedOriginalFileName = "";
                var loadedTempFilePath = "";
                var loadedTempFilePathAndFileName = "";

                loadedOriginalFileName = "aid" + art.ArtId + "-" + Guid.NewGuid();

                if (!Directory.Exists(Path.Combine(webRoot, "tempImages")))
                {
                    Directory.CreateDirectory(Path.Combine(webRoot, "tempImages"));
                }
                loadedTempFilePath = Path.Combine(webRoot, "tempImages");

                loadedTempFilePathAndFileName = Path.Combine(loadedTempFilePath, loadedOriginalFileName);

                //save file from view to disc
                using (var fileStream = new FileStream(loadedTempFilePathAndFileName, FileMode.Create))
                {
                    await ImgFile.CopyToAsync(fileStream);
                }

                //date folder must create one time to all article picture if the date change in meantime
                var pictureFolderDirectory = ImagePathBuilderClass.ImagePathBuilder(webRoot);

                //Retrive relative picture folder directory
                int startPosToSelect = pictureFolderDirectory.IndexOf("wwwroot/Upload", System.StringComparison.CurrentCultureIgnoreCase);
                string relativePictureFolderDirectory = pictureFolderDirectory.Substring(startPosToSelect + 8); //cut after "wwwroot/"
                art.ImagePath = relativePictureFolderDirectory;

                art.ImageWidths = DefineImageSizesClass.DefineImageSizes(ImgFile, loadedTempFilePathAndFileName, pictureFolderDirectory, loadedOriginalFileName);


                art.ImageName = loadedOriginalFileName; //originalFilename;

                art.Created = DateTime.UtcNow;
                art.Updated = DateTime.UtcNow;
                //if (art.Created == DateTime.MinValue) //check if already created
                //{
                //    art.Created = DateTime.Now;
                //}

                DeleteOriginalTempFileClass.DeleteOriginalTempFile(loadedTempFilePathAndFileName); //loadedFilePathAndFileName);

                _context.Add(art);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(art);
        }

        // GET: Art/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var art = await _context.Arts.FindAsync(id);


            if (art == null)
            {
                return NotFound();
            }
            return View(art); 
        }

        // POST: Art/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ArtId,Name,Artist,Description,Price,PriceText,ImageName,ImagePath,ImageWidths,ImageOriginal,Hidden")] Art art, IFormFile ImgFile)
        {
            if (id != art.ArtId)
            {
                return NotFound();
            }

            //Loading/show current picture
            string imagePathAndName = art.ImagePath;
            imagePathAndName += "/" + art.ImageName;
            ViewBag.imagePathAndName = imagePathAndName;

            //Get application directory
            string webRoot = _env.WebRootPath;
            string contentRootPath = _env.ContentRootPath;

            if (ModelState.IsValid)
            {
                if (ImgFile != null && ImgFile.Length != 0)
                {

                    var loadedOriginalFileName = "";
                    var loadedTempFilePath = "";
                    var loadedTempFilePathAndFileName = "";

                    loadedOriginalFileName = "aid" + art.ArtId + "-" + Guid.NewGuid();

                    if (!Directory.Exists(Path.Combine(webRoot, "tempImages")))
                    {
                        Directory.CreateDirectory(Path.Combine(webRoot, "tempImages"));
                    }
                    loadedTempFilePath = Path.Combine(webRoot, "tempImages");
                    loadedTempFilePathAndFileName = Path.Combine(loadedTempFilePath, loadedOriginalFileName);

                    //save file from view to disc
                    using (var fileStream = new FileStream(loadedTempFilePathAndFileName, FileMode.Create))
                    {
                        await ImgFile.CopyToAsync(fileStream);
                    }

                    //date folder must create one time to all article picture if the date change in meantime
                    var pictureFolderDirectory = ImagePathBuilderClass.ImagePathBuilder(webRoot);
                    //Retrive relative picture folder directory
                    int startPosToSelect = pictureFolderDirectory.IndexOf("wwwroot/Upload", System.StringComparison.CurrentCultureIgnoreCase);
                    string relativePictureFolderDirectory = pictureFolderDirectory.Substring(startPosToSelect + 8); //cut after wwwroot/
                    //save old path to delete old pics
                    var oldFilePath = art.ImagePath;
                    //new fresh path
                    art.ImagePath = relativePictureFolderDirectory;

                    //create new pictures
                    art.ImageWidths = DefineImageSizesClass.DefineImageSizes(ImgFile, loadedTempFilePathAndFileName, pictureFolderDirectory, loadedOriginalFileName);


                    var oldFileNameToDelete = art.ImageName;//get old pic name

                    art.ImageName = loadedOriginalFileName; //Filename from update picture download;

                    _deleteArtImages.DeleteImages(oldFilePath, oldFileNameToDelete);

                    DeleteOriginalTempFileClass.DeleteOriginalTempFile(loadedTempFilePathAndFileName);
                }

                art.Updated = DateTime.UtcNow;
                art.Created = await _context.Arts.Where( a => a.ArtId == id).Select(a=>a.Created).FirstOrDefaultAsync() ;

                try
                {

                    _context.Update(art);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArtExists(art.ArtId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(art);
        }

        // GET: Art/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var art = await _context.Arts
                .FirstOrDefaultAsync(m => m.ArtId == id);
            if (art == null)
            {
                return NotFound();
            }

            return View(art);
        }

        // POST: Art/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

Controllers/CollectionArtController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Models;

namespace ArtManager.Controllers
{
    public class CollectionArtController : Controller
    {
        private readonly ArtContext _context;

        public CollectionArtController(ArtContext context)
        {
            _context = context;
        }

        // GET: CollectionArt
        public async Task<IActionResult> Index()
        {
            var artContext = _context.CollectionArts
                .Include(c => c.Art)
                .Include(c => c.Collection)
                .OrderBy(o => o.CollectionId)
                .ThenBy(o => o.ArtId);
            return View(await artContext.ToListAsync());
        }

        // GET: CollectionArt/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var collectionArt = await _context.CollectionArts
                .Include(c => c.Collection)
                .OrderBy(o => o.CollectionId)
                .Include(c => c.Art)
                .OrderBy(o => o.ArtId)
                .FirstOrDefaultAsync(m => m.CollectionId == id);
            if (collectionArt == null)
            {
                return NotFound();
            }

            return View(collectionArt);
        }

        // GET: CollectionArt/Create
        public IActionResult Create()
        {
            ViewData["ArtId"] = new SelectList(_context.Arts, "ArtId", "ArtId");
            ViewData["CollectionId"] = new SelectList(_context.Collections, "CollectionId", "CollectionId");
            return View();
        }

        // POST: CollectionArt/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ArtId,CollectionId")] CollectionArt collectionArt)
        {
            if (ModelState.IsValid)
            {
                _context.Add(collectionArt);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArtId"] = new SelectList(_context.Arts, "ArtId", "ArtId", collectionArt.ArtId);
            ViewData["CollectionId"] = new SelectList(_context.Collections, "CollectionId", "CollectionId", collectionArt.CollectionId);
            return View(collectionArt);
        }

        // GET: CollectionArt/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var collectionArt = await _context.CollectionArts.FindAsync(id);
            if (collectionArt == null)
            {
                return NotFound();
            }
            ViewData["ArtId"] = new SelectList(_context.Arts, "ArtId", "ArtId", collectionArt.ArtId);
            ViewData["CollectionId"] = new SelectList(_context.Collections, "CollectionId", "CollectionId", collectionArt.CollectionId);
            return View(collectionArt);
        }

        // POST: CollectionArt/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ArtId,CollectionId")] CollectionArt collectionArt)
        {
            if (id != collectionArt.CollectionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(collectionArt);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CollectionArtExists(collectionArt.CollectionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(collectionArt);
        }

        // GET: CollectionArt/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var collectionArt = await _context.CollectionArts
                .Include(c => c.Art)
                .Include(c => c.Collection)
                .FirstOrDefaultAsync(m => m.CollectionId == id);
            if (collectionArt == null)
            {
                return NotFound();
            }

            return View(collectionArt);
        }

        // POST: CollectionArt/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var collectionArt = await _context.CollectionArts.FindAsync(id);
            _context.CollectionArts.Remove(collectionArt);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CollectionArtExists(int id)
        {
            return _context.CollectionArts.Any(e => e.CollectionId == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - ArtManager</title>

        <environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ArtManager</a>
                </div>
                <div class="container-fluid"> @*class="navbar-collapse collapse">*@
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Collections
                            <span class="caret"></span></a>

                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Collections" asp-action="Index">Collections</a></li>
                                <li><a asp-area="" asp-controller="CollectionArt" asp-action="Index">CollectionArt</a></li>
                            </ul>
                    </li>
                    <li><a asp-area="" asp-controller="Art" asp-action="Index">Art repository</a></li>

                </ul>
                </div>
            </div>
        </nav>

        <partial name="_CookieConsentPartial" />

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2018 - ArtManager</p>
            </footer>
        </div>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("Scripts", required: false)
    </body>
</html>