Models/Art.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace Models
{
    public class Art
    {

        public int ArtId { get; set; }
        public string Name { get; set; }
        public string Artist { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string PriceText { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public string ImageWidths { get; set; }
        public string ImageOriginal { get; set; }
        public bool Hidden { get; set; }

        public DateTime Created { get; set; }
      
        //[DataType(DataType.DateTime)]
        public DateTime Updated { get; set; }


        public IEnumerable<CollectionArt> CollectionArts { get; set; }
    }
}

Models/Collection.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using ViewModels;

namespace Models
{
    public class Collection
    {
        
        public int CollectionId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        //[DataType(DataType.DateTime)]
        //[DisplayFormat(DataFormatString = "{yyyy MM dd HH:mm:ss}" )]
        public DateTime Created { get; set; }
        //[DataType(DataType.DateTime)]
        //[DisplayFormat(DataFormatString = "{yyyy MM dd HH:mm:ss}")]
        public DateTime Updated { get; set; }
        public bool Hidden { get; set; }

        //public ICollection<CollectionArt> Arts { get; set; } = new List<CollectionArt>();
        public IEnumerable<CollectionArt> CollectionArts { get; set; }

        //public IEnumerable<CollectionArt> CollectionArt { get; internal set; }
    }
}

Controllers/CollectionsController.cs
using System;
//using System.Collection;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Data;
//using System.Data.Entity;
//using System.Data.Entity.EntityState.Modified;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
//using Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper;
using Microsoft.EntityFrameworkCore;
using Models;
using ViewModels;
using ArtManager.Models;
using static System.Linq.Enumerable;
using System.Collections;

namespace ArtManager.Controllers
{

    public class CollectionsController : Controller
    {

        CollectionEditVM collectionEditVM = new CollectionEditVM();
        CollectionEditArtsVM collectionEditArtsVM = new CollectionEditArtsVM();

        private readonly ArtContext _context;

        public CollectionsController(ArtContext context)
        {
            _context = context;
        }

      

        // GET: Collections
        public async Task<IActionResult> Index()
        {
            return View(await _context.Collections.ToListAsync());
        }




        ////------------------------------
        //Get 
        public async Task<IActionResult> Art(int? id)
        {
            CollectionAddArtVM collectionAddArtVM = new CollectionAddArtVM();

            if (id == null)
            {
                return NotFound();
            }

            //hämtar alla bilder från db till view
            List<Art> arts = await _context.Arts.ToListAsync();
          

            collectionEditArtsVM.AllArts = arts;


            var collectionsArt = _context.Arts.Where(s => s.CollectionArts.Any(i => i.CollectionId == id)).ToList();
            collectionEditArtsVM.CollectionsArt = collectionsArt;//(Models.Art)collectionsArt;


            //var collectionsArtList = collectionsArt.ToList();

            //exclude current art in current collection and keep the rest of art to display
            IEnumerable<Art> allArtExceptCollections = arts.Where(x => !collectionsArt.Select(c => c.ArtId).Contains(x.ArtId));

            //remove preselected checkboxes
            foreach (var a in allArtExceptCollections)
            {
                a.Hidden = false;
            }

            //bring current collection
            var collection = await _context.Collections.FindAsync(id);
            if (collection == null)
            {
                return NotFound();
            }

            if (allArtExceptCollections != null)
            {
                collectionEditArtsVM.AllArtExceptCurrent = allArtExceptCollections.ToList();
            }

            collectionEditArtsVM.AllArtExceptCurrent = allArtExceptCollections.ToList();

            collectionEditArtsVM.Collection = collection;

            return View(collectionEditArtsVM);
            //return View(arts);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Art(int id, CollectionEditArtsVM _collectionEditArtsVM)
        {

            if (ModelState.IsValid && _collectionEditArtsVM != null)
            {

                //linq get all Art that belongs actual collection from db
                var collectionsArt = _context.Arts.Where(s => s.CollectionArts.Any(i => i.CollectionId == id)).ToList();

                //adding choosed Art to choosedArt list 
                List<Art> choosedArt = new List<Art>();
                //for (var i = 0; i < _collectionEditArtsVM.AllArts.Count(); i++)
                for (var i = 0; i < _collectionEditArtsVM.AllArtExceptCurrent.Count(); i++)
                {
                    //not the Art already existed in actual collection
                    if (_collectionEditArtsVM.AllArtExceptCurrent[i].Hidden == true)
                    {
                        if (! collectionsArt.Any(x => x.ArtId == _collectionEditArtsVM.AllArtExceptCurrent[i].ArtId))
                        {
                            choosedArt.Add(_collectionEditArtsVM.AllArtExceptCurrent[i]);
                        }
                    }
                }

                //coupling Art and actual collection with its id to one CollectionArt-object.
                var c = choosedArt.Count();
                var colArt = new List<CollectionArt>();

                for (var i = 0; i < c; i++)//foreach (Art item in choosedArt)
                {
                    colArt.Add(new CollectionArt { ArtId = choosedArt[i].ArtId, CollectionId = id });
                }

                //transfer Art to CollectionArt table in db 
                foreach(CollectionArt ca in colArt)
                {
                    _context.CollectionArts.Add(ca);
                }

                _context.SaveChangesAsync();

            }

            return View(_collectionEditArtsVM);
        }


        // GET: Collections/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var collection = await _context.Collections
                .FirstOrDefaultAsync(m => m.CollectionId == id);
            if (collection == null)
            {
                return NotFound();
            }

            IQueryable<CollectionArt> artInCollection = _context.CollectionArts.Where(c=>c.CollectionId == id);

            ViewData["arts"] = artInCollection.ToList();

            return View(collection);
        }

        // GET: Collections/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Collections/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CollectionId,Name,Description,Created,Updated,Hidden,CollectionArt,ArtId")] Collection collection)
        {
            if (ModelState.IsValid)
            {
                collection.Created = DateTime.UtcNow;

                _context.Add(collection);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(collection);
        }


        // GET: Collections/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var collection = await _context.Collections.FindAsync(id);
            if (collection == null)
            {
                return NotFound();
            }


            //get all Art
            List<Art> art = _context.Arts.AsNoTracking<Art>().ToList();
            collectionEditVM.AllArts = art;

            //bring Art that belongs actual collection 
            List<Art> collectionsArt = _context.Arts.Where(s => s.CollectionArts.Any(i => i.CollectionId == id)).ToList();
            collectionEditVM.CollectionsArt = collectionsArt;

            collectionEditVM.Collection = collection;//populate the usual textboxes etc in Collection Edit View by VM


            //ViewData["ArtId"] = new SelectList((System.Collections.IEnumerable)collectionsArt, "ArtId", "Name");

            return View(collectionEditVM);
        }


        // POST: Collections/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CollectionEditVM _collection)
        {

            if (ModelState.IsValid)
            {

                _collection.Collection.Updated = DateTime.UtcNow;

                Collection collection = new Collection();

                collection = _collection.Collection;
                try
                {

                    _context.Update(collection);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CollectionExists(_collection.Collection.CollectionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }


            return View(_collection);
        }


        //public async Task <IActionResult> RemoveArt2(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var collection = await _context.Collections
        //        .FirstOrDefaultAsync(m => m.CollectionId == id);
        //    if (collection == null)
        //    {
        //        return NotFound();
        //    }

        //    //get art that belonging current collection 
        //    List<Art> collectionsArt = _context.Arts.Where(s => s.CollectionArts.Any(i => i.CollectionId == id)).ToList();
        //    collectionEditVM.CollectionsArt = collectionsArt;
        //    collectionEditVM.Collection = collection;


        //    return View(collectionEditVM);
        //}

        //separate Post and Get not needed
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task <IActionResult> RemoveArt(int id, int artId)
        {

            //var collectionArt = await _context.CollectionArts.FirstOrDefaultAsync(c => c.CollectionId == id);
            //var collectionArt = _context.CollectionArts.Find(Collection.CollectionId == id) Model.Art.ArtId == artId;
            CollectionArt _collectionArtToRemove = new CollectionArt { CollectionId = id, ArtId = artId };
          
            _context.CollectionArts.Remove(_collectionArtToRemove);

            //_context.Collections

            await _context.SaveChangesAsync();


            var collection = await _context.Collections

Views/Collections/AddArt.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Collections/Art.cshtml
@model ViewModels.CollectionEditArtsVM


<h3>Add art to collection</h3>

<body>

    <form asp-action="Art" asp-controller="Collections" method="post">

        @if (Model.AllArtExceptCurrent != null)
        {

            for (var i = 0; i < Model.AllArtExceptCurrent.Count(); i++)
            {   
            <div id="divItem">
                <div>
                    <img src="~/@Url.Content(Model.AllArtExceptCurrent.ElementAt(i).ImagePath + "/" + Model.AllArtExceptCurrent.ElementAt(i).ImageName + "-256.jpg")" Style="Width: 200px" alt="image" />
                </div>
                <div id="oneRow">

                    <input type="text" id="artid" asp-for="@Model.AllArtExceptCurrent[i].ArtId" style="border:none" readonly="readonly" />
                    <input type="text" id="PicName" asp-for="@Model.AllArtExceptCurrent[i].Name" style="border:none" readonly="readonly" />

                    <input type="hidden" asp-for="@Model.AllArtExceptCurrent[i].ImagePath" />
                    <input type="hidden" asp-for="@Model.AllArtExceptCurrent[i].Artist" />
                    <input type="hidden" asp-for="@Model.AllArtExceptCurrent[i].ImageName" />
                    <input type="hidden" asp-for="@Model.AllArtExceptCurrent[i].ImageOriginal" />
                    <input type="hidden" asp-for="@Model.AllArtExceptCurrent[i].ImageWidths" />
                    <input type="hidden" asp-for="@Model.AllArtExceptCurrent[i].Description" />
                    <input type="hidden" asp-for="@Model.AllArtExceptCurrent[i].Created" />
                    <input type="hidden" asp-for="@Model.AllArtExceptCurrent[i].Price" />
                    <input type="hidden" asp-for="@Model.AllArtExceptCurrent[i].PriceText" />
                    <input type="hidden" asp-for="@Model.AllArtExceptCurrent[i].Updated" />

                </div>
                <div class="chk">
                    <input type="checkbox" asp-for="@Model.AllArtExceptCurrent[i].Hidden" />

                    <label>Choose this</label>
                </div>
            </div>
            }
        }
        <p id="clearFloat" />

        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-default" />
            <p></p>
            <a asp-action="Edit" asp-route-id="@Model.Collection.CollectionId">Back to Edit </a>

        </div>

        <div id="divCollectionInfo">
            <div class="divCollection">
                <label class="lblCollection" asp-for="Collection.CollectionId"></label>
                <span><input class="txtCollection" type="text" asp-for="Collection.CollectionId" readonly="@(true)" style="border:none" /></span>
            </div>
            <div class="divCollection">
                <label class="lblCollection" asp-for="Collection.Name"></label>
                <span><input class="txtCollection" type="text" asp-for="Collection.Name" readonly="@(true)" style="border:none" /></span>
            </div>
            <div class="divCollection">

                <label class="lblCollection" asp-for="Collection.Description"></label>
                <span><input class="txtCollection" type="text" asp-for="Collection.Description" readonly="@(true)" style="border:none" /></span>
            </div>
        </div>


    </form>

</body>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<style>
    #divItem {
        width: 210px;
        float: left;
        padding: 5px;
        border: 1px;
        border-collapse: collapse;
        margin: 5px;
        outline-color: lightgray;
        outline-width: 1px;
        outline-style: solid;
    }
    #artid {
        float: left;
        margin-right: 10px;
        width:5%;
    }

    #oneRow {
        display: flex;
        flex-direction: row;
        /*display:inline-block;*/
    }

    img {
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 50%;
    }
    /*
    #PicName {
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 90%;
    }
        */
    #clearFloat {
        clear: left;
    }
    

    input[type='checkbox'] {
        float: left;
        margin-right: 10px;
    }

    .txtCollection {
        float: right;
        margin-left: 10px;
    }

    .divCollection {

        display: flex;
        /*flex-direction: row;*/
        /*display: inline-block;*/
    }
    .lblCollection {
        display: inline-block;
        width: 100px;
        text-align:right;
    }
    #divCollectionInfo {
        /*width: 30%;
        padding: 5px;
        outline-color: lightgray;
        outline-width: 1px;
        outline-style: solid;*/

    }
      


</style>


Views/Collections/Create.cshtml
@model Models.Collection

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Collection</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="Created" class="control-label"></label>
                <input asp-for="Created" class="form-control" />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Updated" class="control-label"></label>
                <input asp-for="Updated" class="form-control" />
                <span asp-validation-for="Updated" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Hidden" /> @Html.DisplayNameFor(model => model.Hidden)
                    </label>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="CollectionArts" class="control-label"></label>
                <input asp-for="CollectionArts" class="form-control"/> @Html.DisplayNameFor(model=>model.CollectionArts)
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Collections/Delete.cshtml
@model Models.Collection

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Collection</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Updated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Updated)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Hidden)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Hidden)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CollectionId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Collections/Details.cshtml
@model Models.Collection

@{
    ViewData["Title"] = "Details";

}

<h2>Details</h2>

<div>
    <h4>Collection</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Updated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Updated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CollectionArts)
        </dt>
        <dd>


            @foreach (var a in ViewData["arts"] as IList<Models.CollectionArt>)
            {
                @("ArtId:" + a.ArtId + " ");
            }


        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CollectionId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Collections/Edit.cshtml
@*@model Models.Collection*@
@model ViewModels.CollectionEditVM

@{
    ViewData["Title"] = "Edit";

    @*ViewData["ArtId"] = "Edit";*@
}

<h2>Edit</h2>

<h4>Collection</h4>
<hr />
<body>
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit" asp-controller="Collections" method="post">

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <input type="hidden" asp-for="Collection.CollectionId" />

                <div class="form-group">
                    <label asp-for="Collection.Name" class="control-label"></label>
                    <input asp-for="Collection.Name" class="form-control" />
                    <span asp-validation-for="Collection.Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Collection.Description" class="control-label"></label>
                    <input asp-for="Collection.Description" class="form-control" />
                    <span asp-validation-for="Collection.Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Collection.Created" class="control-label"></label>
                    <input asp-for="Collection.Created" class="form-control" readonly="@(true)" />
                    <span asp-validation-for="Collection.Created" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Collection.Updated" class="control-label"></label>
                    <input asp-for="Collection.Updated" class="form-control" readonly="@(true)" />
                    <span asp-validation-for="Collection.Updated" class="text-danger"></span>
                </div>


                <div class="form-group">
                    <a asp-action="Art" asp-route-id="@Model.Collection.CollectionId">Get more pictures </a>
                </div>


                <p id="clearFloat" />
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>

            </form>
        </div>

        <p id="clearFloat"></p>

        <hr />


        @if (Model.CollectionsArt != null)
        {

            for (var i = 0; i < Model.CollectionsArt.Count(); i++)
            {
        <div id="divItem">
            <div id="innerBlock">
                <img src="~/@Url.Content(Model.CollectionsArt.ElementAt(i).ImagePath + "/" + Model.CollectionsArt.ElementAt(i).ImageName + "-256.jpg")" Style="Width: 200px;" alt="image" />
            </div>
            <div id="oneRow">

                <input type="text" id="artid" asp-for="@Model.CollectionsArt[i].ArtId" style="border:none" readonly="readonly" />
                <input type="text" id="PicName" asp-for="@Model.CollectionsArt[i].Name" style="border:none" readonly="readonly" />

            </div>

            <a asp-action="RemoveArt" asp-route-id="@Model.Collection.CollectionId" asp-route-artId="@Model.CollectionsArt[i].ArtId" >Remove art</a>

        </div>
            }
        }

    <p id = "clearFloat" ></p>


</div>
                

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

</body>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<style>
    #innerBlock {
        /*display: inline-block;
        float: left;*/
    }
    #divItem {
        /*display: inline-block;*/
        width: 210px;
        float: left;
        padding: 5px;
        border: 1px;
        border-collapse: collapse;
        margin: 5px;
        outline-color: lightgray;
        outline-width: 1px;
        outline-style: solid;
    }
    #oneRow {
        display: flex;
        flex-direction: row;
        /*display:inline-block;*/
    }
    #artid {
        float: left;
        margin-right: 10px;
        width: 5%;
    }
    img {
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 50%;
    }
    #clearFloat {
        clear: left;
    }
</style>

Views/Collections/Index.cshtml
@model IEnumerable<Models.Collection>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Created)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Updated)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.Hidden)
            </th>*@
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Created)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Updated)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Hidden)
            </td>*@
            <td>
                <a asp-action="Edit" asp-route-id="@item.CollectionId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CollectionId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CollectionId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Collections/RemoveArt.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model ViewModels.CollectionEditVM

@{

}


<h3>Remove pictures from current collection</h3>

<body>


    <p id="clearFloat"></p>

    <hr />


    @if (Model.CollectionsArt != null)
    {

        for (var i = 0; i < Model.CollectionsArt.Count(); i++)
        {
            <div id="divItem">
                <div id="innerBlock">
                    <img src="~/@Url.Content(Model.CollectionsArt.ElementAt(i).ImagePath + "/" + Model.CollectionsArt.ElementAt(i).ImageName + "-256.jpg")" Style="Width: 200px;" alt="image" />
                </div>
                <div id="oneRow">

                    <input type="text" id="artid" asp-for="@Model.CollectionsArt[i].ArtId" style="border:none" readonly="readonly" />
                    <input type="text" id="PicName" asp-for="@Model.CollectionsArt[i].Name" style="border:none" readonly="readonly" />

                </div>

                @Html.ActionLink("Remove", "RemoveArt", "Collections", new { id = Model.Collection.CollectionId, artId = Model.CollectionsArt[i].ArtId }, null)


            </div>
        }
    }

    <p id="clearFloat"></p>



    <div>
        <a asp-action="Edit" asp-route-id="@Model.Collection.CollectionId">Back to Edit</a>
    </div>

</body>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<style>
    #innerBlock {
        /*display: inline-block;
        float: left;*/
    }

    #divItem {
        /*display: inline-block;*/
        width: 210px;
        float: left;
        padding: 5px;
        border: 1px;
        border-collapse: collapse;
        margin: 5px;
        outline-color: lightgray;
        outline-width: 1px;
        outline-style: solid;
    }

    #oneRow {
        display: flex;
        flex-direction: row;
        /*display:inline-block;*/
    }

    #artid {
        float: left;
        margin-right: 10px;
        width: 5%;
    }

    img {
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 50%;
    }

    #clearFloat {
        clear: left;
    }
</style>

Views/Collections/SelectArt.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model ViewModels.CollectionEditArtsVM

<form action="/ViewModels/CollectionEditArtsVM" method="post">


    @foreach (var item in Model.AllArts)
    {

        <img src="~/@Url.Content(item.ImagePath + "/" + item.ImageName + "-256.jpg")" alt="Image" style="width: 180px" />


        <input id="ChkImageName" name="checkImage" type="checkbox" value="true" />
        <input name="checkImage" type="hidden" value="false" />


        <input type="submit" value="Login" />
    }
   


</form>